@set allusersprofile=c:\programdata
@set appdata=c:\users\shrek\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-0gm2goq
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64\
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set homedrive=c:
@set homepath=\users\shrek
@set include=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.22.27905\atlmfc\include;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.22.27905\include;c:\program files (x86)\windows kits\netfxsdk\4.7.2\include\um;c:\program files (x86)\windows kits\10\include\10.0.18362.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.18362.0\shared;c:\program files (x86)\windows kits\10\include\10.0.18362.0\um;c:\program files (x86)\windows kits\10\include\10.0.18362.0\winrt;c:\program files (x86)\windows kits\10\include\10.0.18362.0\cppwinrt
@set lib=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.22.27905\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.22.27905\lib\x64;c:\program files (x86)\windows kits\netfxsdk\4.7.2\lib\um\x64;c:\program files (x86)\windows kits\10\lib\10.0.18362.0\ucrt\x64;c:\program files (x86)\windows kits\10\lib\10.0.18362.0\um\x64
@set libpath=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.22.27905\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.22.27905\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.22.27905\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.18362.0;c:\program files (x86)\windows kits\10\references\10.0.18362.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\shrek\appdata\local
@set logonserver=\\desktop-0gm2goq
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.7.2\
@set number_of_processors=2
@set onedrive=c:\users\shrek\onedrive
@set onedriveconsumer=c:\users\shrek\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.22.27905\bin\hostx64\x64;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2019\community\msbuild\current\bin\roslyn;c:\program files (x86)\microsoft visual studio\2019\community\team tools\performance tools\x64;c:\program files (x86)\microsoft visual studio\2019\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\\x64;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.7.2 tools\x64\;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x64;c:\program files (x86)\windows kits\10\bin\x64;c:\program files (x86)\microsoft visual studio\2019\community\\msbuild\current\bin;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.22.27905\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.7.2 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.7.2 tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\git\cmd;c:\program files\microsoft sql server\130\tools\binn\;c:\windows\system32\openssh\;c:\program files\cmake\bin;c:\program files\nodejs\;c:\users\shrek\appdata\local\programs\python\python37-32\scripts;c:\users\shrek\appdata\local\programs\python\python37-32;c:\program files (x86)\brackets\command;c:\program files\dotnet\;c:\program files\putty\;c:\program files\mysql\mysql shell 8.0\bin\;c:\users\shrek\appdata\local\microsoft\windowsapps;c:\program files\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin;c:\users\shrek\appdata\roaming\npm;c:\program files\jetbrains\pycharm community edition 2019.2.1\bin;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\ninja
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\shrek\appdata\local\microsoft\visualstudio\16.0_1ff684e7\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 76 stepping 3, genuineintel
@set processor_level=6
@set processor_revision=4c03
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtools_extensionspath_vs2017=c:\program files (x86)\microsoft visual studio\2017\enterprise\msbuild
@set pvsbuildtools_extensionspath_vs2019=c:\program files (x86)\microsoft visual studio\2019\community\msbuild
@set pvsbuildtools_installdir_vs2017=c:\program files (x86)\microsoft visual studio\2017\enterprise
@set pvsbuildtools_installdir_vs2019=c:\program files (x86)\microsoft visual studio\2019\community
@set pvs_netcoresdkspath=c:\program files\dotnet\sdk\2.1.801\sdks
@set pycharm community edition=c:\program files\jetbrains\pycharm community edition 2019.2.1\bin
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\shrek\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\shrek\appdata\local\temp
@set ucrtversion=10.0.18362.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-0gm2goq
@set userdomain_roamingprofile=desktop-0gm2goq
@set username=shrek
@set userprofile=c:\users\shrek
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.22.27905\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2019\community\vc\redist\msvc\14.22.27821\
@set vctoolsversion=14.22.27905
@set visualstudiodir=c:\users\shrek\documents\visual studio 2019
@set visualstudioedition=microsoft visual studio communityÿ2019
@set visualstudioversion=16.0
@set vs150entcomntools=c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\tools\
@set vs160comcomntools=c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\
@set vs160comntools=c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=16.2.3
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\
@set vslang=1049
@set vsskuedition=community
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.18362.0;c:\program files (x86)\windows kits\10\references\10.0.18362.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.18362.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.18362.0\
@set windowssdkversion=10.0.18362.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.7.2 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.7.2 tools\
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.22.27905\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.7.2 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.18362.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.7.2 tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\git\cmd;c:\program files\microsoft sql server\130\tools\binn\;c:\windows\system32\openssh\;c:\program files\cmake\bin;c:\program files\nodejs\;c:\users\shrek\appdata\local\programs\python\python37-32\scripts;c:\users\shrek\appdata\local\programs\python\python37-32;c:\program files (x86)\brackets\command;c:\program files\dotnet\;c:\program files\putty\;c:\program files\mysql\mysql shell 8.0\bin\;c:\users\shrek\appdata\local\microsoft\windowsapps;c:\program files\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin;c:\users\shrek\appdata\roaming\npm;c:\program files\jetbrains\pycharm community edition 2019.2.1\bin

@call "cl.exe" @"C:\Users\shrek\source\repos\Radix my love\Radix_my_love.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1